### PR TITLE
Allow user create subscription items

### PR DESCRIPTION
**Pull request by suhiltzaile**
Same as title

### CODE REVIEW

**Comment by xxswingxx** [comment]
I've been wondering if the paypal related fields should be exposed with the `paypal_subscription_` preffix (or something similar like in the CSV import file). For example, it might be a bit confusing having just `interval_frequency` and it's not very coherent with the other gateway fields, (ie. `stripe_id`) and also in case we add new gateways in the future, we could have problems with that naming. What do you think @suhiltzaile @polimorfico ?

**Comment by suhiltzaile** [comment]
Definitely makes sense for me

**Comment by polimorfico** [comment]
100% agreed

**Comment by suhiltzaile** [comment]
Ready to be merged :-)

**Pull request merged**
